# Generated by Django 3.2.5 on 2022-08-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('iban', models.TextField()),
                ('type_account_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
    ]
