# Generated by Django 3.2.5 on 2022-08-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False, 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
    ]
