# Generated by Django 4.1 on 2022-08-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Direccion",
            fields=[
                ("direccion_id", models.AutoField(primary_key=True, serialize=False)),
                ("numero", models.IntegerField()),
                ("calle", models.TextField()),
                ("ciudad", models.TextField()),
                ("provincia", models.TextField()),
                ("pais", models.TextField()),
            ],
            options={
                "db_table": "direccion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("employee_name", models.TextField()),
                ("employee_surname", models.TextField()),
                ("employee_hire_date", models.TextField()),
                ("employee_dni", models.TextField(db_column="employee_DNI")),
                ("branch_id", models.IntegerField()),
                ("employee_direccion_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "empleado",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tarjeta",
            fields=[
                ("card_id", models.AutoField(primary_key=True, serialize=False)),
                ("card_number", models.TextField()),
                ("card_expire", models.TextField()),
                ("card_expire_date", models.TextField()),
                ("card_cvv", models.IntegerField()),
                ("card_type", models.TextField()),
                ("customer_id", models.IntegerField()),
            ],
            options={
                "db_table": "tarjeta",
                "managed": False,
            },
        ),
    ]
