# Generated by Django 3.2.5 on 2022-08-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.IntegerField()),
                ('card_expire', models.IntegerField()),
                ('card_expire_date', models.IntegerField()),
                ('card_cvv', models.IntegerField()),
                ('card_type', models.TextField()),
                ('customer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
    ]
