# Generated by Django 3.2.5 on 2022-08-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'managed': False, 'verbose_name': 'prestamo', 'verbose_name_plural': 'prestamos'},
        ),
    ]
